# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31b427d78877097bb4a08849f3f12ee16ace1994bbf392f536e7c1e1c5476a670e54394b40affa5d56fce686e96d21115175a899a24239b62cd4d05914e8da71

test:
  secret_key_base: b1975165b015942f280deb7905dc5445e71018f805bbc9e66b91bf09d463da695b3234b3b100725bc926c8cdc8bd24e19467b7f11b8722c18982dc7802296d51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
